version: "3.3"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    volumes:
      - ./.build/openapi.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json

  swagger-api:
    image: danielgtaylor/apisprout
    container_name: "swagger-api"
    ports:
      - "8083:8000"
    volumes:
      - ./.build/openapi.json:/openapi.json
    command: /openapi.json
