openapi: "3.0.0"
info:
  title: Uberoo API
  description: |
    To manage restaurants, menus, delivery people and orders with the Uberoo REST API.  
    You can find out more about Uberoo at [uberoo.eat](https://uberoo.eat) and developer documentation at [developers.uberoo.eat](https://developers.uberoo.eat).

    # Authentication
    ## Bearer
    To authenticate you need to send a `Bearer <JWT>` token in the `Authorization` header.  
    To find more information about JWT, you can find out more at [https://jwt.io](https://jwt.io).  
    You can generate a JWT token using the `/account/login` endpoint.
  version: "1.0.0"
  termsOfService: http://api.uberoo.eat/terms/
  contact:
    name: Uberoo API Team
    email: apiteam@uberoo.eat
    url: https://api.uberoo.eat/contact/
externalDocs:
  description: Github repository
  url: "https://github.com/av1m/uberoo-api"
servers:
  - url: "http://localhost:8000"
    description: "Local server"
  - url: "http://api-sandbox.uberoo.eat"
    description: "Sandbox server"
  - url: "http://api-staging.uberoo.eat"
    description: "Staging server"
  - url: "https://api.uberoo.eat"
    description: "Production server"
tags:
  - name: restaurants
    description: "Manage restaurants"
  - name: foods
    description: "Manage foods and menus of restaurants"
  - name: carts
    description: "Manage carts / baskets of customers"
  - name: orders
    description: "Manage orders of customers"
  - name: accounts
    description: "Manage accounts : authentication, registration, reset password"
  - name: users
    description: "Manage users of Uberoo. Theses endpoints are for all users. Check specific type user for more information"
  - name: payments
    description: "Manage payments of orders"
  - name: notifications
    description: "Manage all notifications, including push notifications, email, SMS and Webhook"
  - name: issues
    description: "Manage issues and feedback"
paths:
  /restaurants/v1/:
    $ref: "./resources/restaurants.yaml"
  /restaurants/v1/{restaurantId}:
    $ref: "./resources/restaurant.yaml"
  /users/v1/{userId}/carts:
    $ref: "./resources/carts.yaml"
  /restaurants/v1/{restaurantId}/foods:
    $ref: "./resources/foods.yaml"
  /restaurants/v1/{restaurantId}/foods/{foodId}:
    $ref: "./resources/food.yaml"
  /orders/v1/:
    $ref: "./resources/orders.yaml"
  /orders/v1/{orderId}:
    $ref: "./resources/order.yaml"
  /accounts/v1/register:
    $ref: "./resources/register.yaml"
  /accounts/v1/login:
    $ref: "./resources/login.yaml"
  /accounts/v1/password:
    $ref: "./resources/password.yaml"
  /users/v1/:
    $ref: "./resources/users.yaml"
  /users/v1/{userId}:
    $ref: "./resources/user.yaml"
components:
  parameters:
    $ref: "./parameters/_index.yaml"
  schemas:
    $ref: "./schemas/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
