openapi: "3.0.0"
info:
  title: Uberoo API
  description: |
    To manage restaurants, menus, delivery people and orders with the Uberoo REST API.  
    You can find out more about Uberoo at [http://uberoo.eat](uberoo.eat).

    # Authentication
    ## JWT
    To authenticate you need to send a `Bearer <JWT>` token in the `Authorization` header.  
    To find more information about JWT, you can find out more at [https://jwt.io](https://jwt.io).  
    You can generate a JWT token using the `/account/login` endpoint.
  version: "1.0.0"
  termsOfService: http://api.uberoo.eat/terms/
  contact:
    name: Uberoo API Team
    email: apiteam@uberoo.eat
    url: https://api.uberoo.eat/contact/
externalDocs:
  description: Github repository
  url: "https://github.com/av1m/uberoo-api"
servers:
  - url: "http://localhost:8000"
    description: "Local server"
  - url: "http://api-sandbox.uberoo.eat"
    description: "Sandbox server"
  - url: "http://api-staging.uberoo.eat"
    description: "Staging server"
  - url: "https://api.uberoo.eat"
    description: "Production server"
tags:
  - name: restaurants
    description: "Manage restaurants"
  - name: foods
    description: "Manage foods and menus of restaurants"
  - name: carts
    description: "Manage carts / baskets of customers"
  - name: orders
    description: "Manage orders of customers"
  - name: accounts
    description: "Manage accounts"
paths:
  /restaurants:
    $ref: "./resources/restaurants.yaml"
  /restaurants/{restaurantId}:
    $ref: "./resources/restaurant.yaml"
  /users/{userId}/carts:
    $ref: "./resources/carts.yaml"
  /restaurants/{restaurantId}/foods:
    $ref: "./resources/foods.yaml"
  /restaurants/{restaurantId}/foods/{foodId}:
    $ref: "./resources/food.yaml"
  /orders:
    $ref: "./resources/orders.yaml"
  /orders/{orderId}:
    $ref: "./resources/order.yaml"
  /accounts/register:
    $ref: "./resources/register.yaml"
  /accounts/login:
    $ref: "./resources/login.yaml"
  /accounts/change-password:
    $ref: "./resources/change-password.yaml"
components:
  parameters:
    $ref: "./parameters/_index.yaml"
  schemas:
    $ref: "./schemas/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
